var Ziggy = {
    namedRoutes: {
        "unisharp.lfm.show": {"uri": "laravel-filemanager", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.getErrors": {"uri": "laravel-filemanager\/errors", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.upload": {
            "uri": "laravel-filemanager\/upload",
            "methods": ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
            "domain": null
        },
        "unisharp.lfm.getItems": {"uri": "laravel-filemanager\/jsonitems", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.move": {"uri": "laravel-filemanager\/move", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.domove": {"uri": "laravel-filemanager\/domove", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.getAddfolder": {
            "uri": "laravel-filemanager\/newfolder",
            "methods": ["GET", "HEAD"],
            "domain": null
        },
        "unisharp.lfm.getFolders": {"uri": "laravel-filemanager\/folders", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.getCrop": {"uri": "laravel-filemanager\/crop", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.getCropimage": {
            "uri": "laravel-filemanager\/cropimage",
            "methods": ["GET", "HEAD"],
            "domain": null
        },
        "unisharp.lfm.getCropnewimage": {
            "uri": "laravel-filemanager\/cropnewimage",
            "methods": ["GET", "HEAD"],
            "domain": null
        },
        "unisharp.lfm.getRename": {"uri": "laravel-filemanager\/rename", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.getResize": {"uri": "laravel-filemanager\/resize", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.performResize": {
            "uri": "laravel-filemanager\/doresize",
            "methods": ["GET", "HEAD"],
            "domain": null
        },
        "unisharp.lfm.getDownload": {
            "uri": "laravel-filemanager\/download",
            "methods": ["GET", "HEAD"],
            "domain": null
        },
        "unisharp.lfm.getDelete": {"uri": "laravel-filemanager\/delete", "methods": ["GET", "HEAD"], "domain": null},
        "unisharp.lfm.": {"uri": "laravel-filemanager\/demo", "methods": ["GET", "HEAD"], "domain": null},
        "authors.admin": {"uri": "admin\/authors\/all", "methods": ["GET", "HEAD"], "domain": null},
        "templates.index": {"uri": "admin\/templates", "methods": ["GET", "HEAD"], "domain": null},
        "templates.create": {"uri": "admin\/templates\/create", "methods": ["GET", "HEAD"], "domain": null},
        "templates.store": {"uri": "admin\/templates", "methods": ["POST"], "domain": null},
        "templates.show": {"uri": "admin\/templates\/{template}", "methods": ["GET", "HEAD"], "domain": null},
        "templates.edit": {"uri": "admin\/templates\/{template}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "templates.update": {"uri": "admin\/templates\/{template}", "methods": ["PUT", "PATCH"], "domain": null},
        "templates.destroy": {"uri": "admin\/templates\/{template}", "methods": ["DELETE"], "domain": null},
        "categories.index": {"uri": "admin\/categories", "methods": ["GET", "HEAD"], "domain": null},
        "categories.create": {"uri": "admin\/categories\/create", "methods": ["GET", "HEAD"], "domain": null},
        "categories.store": {"uri": "admin\/categories", "methods": ["POST"], "domain": null},
        "categories.show": {"uri": "admin\/categories\/{category}", "methods": ["GET", "HEAD"], "domain": null},
        "categories.edit": {"uri": "admin\/categories\/{category}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "categories.update": {"uri": "admin\/categories\/{category}", "methods": ["PUT", "PATCH"], "domain": null},
        "categories.destroy": {"uri": "admin\/categories\/{category}", "methods": ["DELETE"], "domain": null},
        "authors.index": {"uri": "admin\/authors", "methods": ["GET", "HEAD"], "domain": null},
        "authors.create": {"uri": "admin\/authors\/create", "methods": ["GET", "HEAD"], "domain": null},
        "authors.store": {"uri": "admin\/authors", "methods": ["POST"], "domain": null},
        "authors.show": {"uri": "admin\/authors\/{author}", "methods": ["GET", "HEAD"], "domain": null},
        "authors.edit": {"uri": "admin\/authors\/{author}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "authors.update": {"uri": "admin\/authors\/{author}", "methods": ["PUT", "PATCH"], "domain": null},
        "authors.destroy": {"uri": "admin\/authors\/{author}", "methods": ["DELETE"], "domain": null},
        "users.index": {"uri": "admin\/users", "methods": ["GET", "HEAD"], "domain": null},
        "users.create": {"uri": "admin\/users\/create", "methods": ["GET", "HEAD"], "domain": null},
        "users.store": {"uri": "admin\/users", "methods": ["POST"], "domain": null},
        "users.show": {"uri": "admin\/users\/{user}", "methods": ["GET", "HEAD"], "domain": null},
        "users.edit": {"uri": "admin\/users\/{user}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "users.update": {"uri": "admin\/users\/{user}", "methods": ["PUT", "PATCH"], "domain": null},
        "users.destroy": {"uri": "admin\/users\/{user}", "methods": ["DELETE"], "domain": null},
        "statuses.index": {"uri": "admin\/statuses", "methods": ["GET", "HEAD"], "domain": null},
        "statuses.create": {"uri": "admin\/statuses\/create", "methods": ["GET", "HEAD"], "domain": null},
        "statuses.store": {"uri": "admin\/statuses", "methods": ["POST"], "domain": null},
        "statuses.show": {"uri": "admin\/statuses\/{status}", "methods": ["GET", "HEAD"], "domain": null},
        "statuses.edit": {"uri": "admin\/statuses\/{status}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "statuses.update": {"uri": "admin\/statuses\/{status}", "methods": ["PUT", "PATCH"], "domain": null},
        "statuses.destroy": {"uri": "admin\/statuses\/{status}", "methods": ["DELETE"], "domain": null},
        "rooms.index": {"uri": "admin\/rooms", "methods": ["GET", "HEAD"], "domain": null},
        "rooms.create": {"uri": "admin\/rooms\/create", "methods": ["GET", "HEAD"], "domain": null},
        "rooms.store": {"uri": "admin\/rooms", "methods": ["POST"], "domain": null},
        "rooms.show": {"uri": "admin\/rooms\/{room}", "methods": ["GET", "HEAD"], "domain": null},
        "rooms.edit": {"uri": "admin\/rooms\/{room}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "rooms.update": {"uri": "admin\/rooms\/{room}", "methods": ["PUT", "PATCH"], "domain": null},
        "rooms.destroy": {"uri": "admin\/rooms\/{room}", "methods": ["DELETE"], "domain": null},
        "events.index": {"uri": "admin\/events", "methods": ["GET", "HEAD"], "domain": null},
        "events.create": {"uri": "admin\/events\/create", "methods": ["GET", "HEAD"], "domain": null},
        "events.store": {"uri": "admin\/events", "methods": ["POST"], "domain": null},
        "events.show": {"uri": "admin\/events\/{event}", "methods": ["GET", "HEAD"], "domain": null},
        "events.edit": {"uri": "admin\/events\/{event}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "events.update": {"uri": "admin\/events\/{event}", "methods": ["PUT", "PATCH"], "domain": null},
        "events.destroy": {"uri": "admin\/events\/{event}", "methods": ["DELETE"], "domain": null},
        "reviews.index": {"uri": "admin\/reviews", "methods": ["GET", "HEAD"], "domain": null},
        "reviews.create": {"uri": "admin\/reviews\/create", "methods": ["GET", "HEAD"], "domain": null},
        "reviews.store": {"uri": "admin\/reviews", "methods": ["POST"], "domain": null},
        "reviews.show": {"uri": "admin\/reviews\/{review}", "methods": ["GET", "HEAD"], "domain": null},
        "reviews.edit": {"uri": "admin\/reviews\/{review}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "reviews.update": {"uri": "admin\/reviews\/{review}", "methods": ["PUT", "PATCH"], "domain": null},
        "reviews.destroy": {"uri": "admin\/reviews\/{review}", "methods": ["DELETE"], "domain": null},
        "editions.index": {"uri": "admin\/editions", "methods": ["GET", "HEAD"], "domain": null},
        "editions.create": {"uri": "admin\/editions\/create", "methods": ["GET", "HEAD"], "domain": null},
        "editions.store": {"uri": "admin\/editions", "methods": ["POST"], "domain": null},
        "editions.show": {"uri": "admin\/editions\/{edition}", "methods": ["GET", "HEAD"], "domain": null},
        "editions.edit": {"uri": "admin\/editions\/{edition}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "editions.update": {"uri": "admin\/editions\/{edition}", "methods": ["PUT", "PATCH"], "domain": null},
        "editions.destroy": {"uri": "admin\/editions\/{edition}", "methods": ["DELETE"], "domain": null},
        "posts.admin": {"uri": "admin\/posts\/all", "methods": ["GET", "HEAD"], "domain": null},
        "posts.link": {"uri": "admin\/posts\/{post}\/link", "methods": ["PATCH"], "domain": null},
        "posts.valid": {"uri": "admin\/posts\/{post}\/validate", "methods": ["PATCH"], "domain": null},
        "posts.reviewer": {"uri": "admin\/posts\/review", "methods": ["GET", "HEAD"], "domain": null},
        "posts.author": {"uri": "admin\/posts", "methods": ["GET", "HEAD"], "domain": null},
        "posts.create": {"uri": "admin\/posts\/create", "methods": ["GET", "HEAD"], "domain": null},
        "posts.store": {"uri": "admin\/posts", "methods": ["POST"], "domain": null},
        "posts.show": {"uri": "admin\/posts\/{post}", "methods": ["GET", "HEAD"], "domain": null},
        "posts.edit": {"uri": "admin\/posts\/{post}\/edit", "methods": ["GET", "HEAD"], "domain": null},
        "posts.update": {"uri": "admin\/posts\/{post}", "methods": ["PUT", "PATCH"], "domain": null},
        "posts.destroy": {"uri": "admin\/posts\/{post}", "methods": ["DELETE"], "domain": null},
        "login": {"uri": "login", "methods": ["GET", "HEAD"], "domain": null},
        "logout": {"uri": "logout", "methods": ["POST"], "domain": null},
        "register": {"uri": "register", "methods": ["GET", "HEAD"], "domain": null},
        "password.request": {"uri": "password\/reset", "methods": ["GET", "HEAD"], "domain": null},
        "password.email": {"uri": "password\/email", "methods": ["POST"], "domain": null},
        "password.reset": {"uri": "password\/reset\/{token}", "methods": ["GET", "HEAD"], "domain": null},
        "password.update": {"uri": "password\/reset", "methods": ["POST"], "domain": null},
        "password.confirm": {"uri": "password\/confirm", "methods": ["GET", "HEAD"], "domain": null},
        "verification.notice": {"uri": "email\/verify", "methods": ["GET", "HEAD"], "domain": null},
        "verification.verify": {"uri": "email\/verify\/{id}\/{hash}", "methods": ["GET", "HEAD"], "domain": null},
        "verification.resend": {"uri": "email\/resend", "methods": ["POST"], "domain": null}
    },
    baseUrl: 'http://unisaresearch.local/',
    baseProtocol: 'http',
    baseDomain: 'unisaresearch.local',
    basePort: false,
    defaultParameters: []
};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (var name in window.Ziggy.namedRoutes) {
        Ziggy.namedRoutes[name] = window.Ziggy.namedRoutes[name];
    }
}

export {
    Ziggy
}
